### ISSUE TITLE
Tagging for visibility

### ISSUE THREAD

**Issue by matmair** [fturati/inventree-cab-plugin#1]
Hi there @fturati!
I am one of the core developers of InvenTree. This plugins looks very interesting. Would you mind adding the `inventree`, `inventreeplugins` tags to this repo? This helps with discovery in the ecosystem as it autogenerates this nice page: https://github.com/topics/inventreeplugins

Cheers, Matthias

**Comment by fturati** [comment]
Hi @matmair,
Thank you for your advice. The tags should have been added.
I also noticed that the tags were not present for the [inventree-brother-plugin](https://github.com/inventree/inventree-brother-plugin), having mostly used this plugin as a reference I missed the fact that other plugins used tags for visibility.
Cheers,

**Comment by matmair** [comment]
Thank you for the info, I totally missed that we did not tag that repo - I have corrected that now!
